### ISSUE TITLE
docs: Explain what --no public-private and --no into-init do

### ISSUE THREAD

**Issue by pawamoy** [15r10nk/canonical-imports#5]
It would be nice to explain a bit more what these two options do in the CLI help, and with examples in the README/docs.

Something like this for public-private:

> By default, canonical-imports will rewrite imports even if their current location is public while their canonical location is private:

>
  ```diff
  -from package.module import Thing
  +from package.module._submodule import Thing
  ```

> You can prevent that by passing the `--no public-private` flag.

I don't know what into-init means :smile:

**Comment by 15r10nk** [comment]
Thank you again.

I have added the documentation for these options.
https://github.com/15r10nk/canonical-imports/tree/docs?tab=readme-ov-file#options

I developed these options because I thought they might be useful.
Please let me know if they make sense to you or if you have other ideas.

**Comment by pawamoy** [comment]
Thanks! These two options definitely make sense, and I've been using the no-public-private one already :slightly_smiling_face: 

I'll send a small suggestion for the second example in the PR!

**Comment by pawamoy** [comment]
(sorry for closing, I thought the PR was already merged)
